name: Flutter Web Build

on:
  push:
    branches: [ 'schuchanek-flutter-mvp', 'main' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
      - name: Install dependencies
        run: |
          cd flutter_app
          flutter pub get
      - name: Build web
        run: |
          cd flutter_app
          flutter build web --release
      - name: Upload web build artifact
        uses: actions/upload-artifact@v4
        with:
          name: web_build
          path: flutter_app/build/web
